language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - mongodb # Start mongodb for functional tests.
  - docker # Enable usage of docker commands.
env:
  global:
    - APP_NAME=create-nodejs-app
    - APP_PROCESS_TYPE=web
    - AUTHORIZATION_TOKEN=authorization-token-test
    - DOCKER_IMAGE_NAME=leonardosarmentocastro/$APP_NAME:$TRAVIS_COMMIT
    - HEROKU_API_KEY=$SECRET_HEROKU_AUTHORIZATION_TOKEN # Needed for Heroku CLI image release.
    - HEROKU_DOCKER_IMAGE_NAME=registry.heroku.com/$APP_NAME/$APP_PROCESS_TYPE
    - NODE_ENV=test
    - MONGODB_DATABASE_NAME=db-ci
    - MONGODB_HOST=0.0.0.0

install: npm ci # Clean/faster install of dependencies.

before_script:
  - sleep 15 # https://docs.travis-ci.com/user/database-setup/#mongodb-does-not-immediately-accept-connections

script:
  - npm run test:ci # Run unit/functional tests using mongodb from "services".

after_success:
  - npx codecov --file=./coverage/lcov.info # Collect code coverage: https://codecov.io

deploy:
  on:
    branch: master
  provider: script
  script: bash ci/deploy.sh
