version: '3'
services:
  database:
    image: mysql:5.7.22
    container_name: agme_mysql
    hostname: 'mysqlhost'
    environment:
      MYSQL_ROOT_PASSWORD: melhorescola
      MYSQL_DATABASE: melhorescola
      MYSQL_USER: melhorescola
      MYSQL_PASSWORD: melhorescola
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1
    ports:
      - 33000:3306
    volumes:
      - ${PWD}/docker/volumes/mysql:/var/lib/mysql
    networks:
      - app-network
        
  server:
    build: .
    depends_on:
      - database
    # Receives variables from "docker-compose up" instruction and attach as nodejs "process.env" variables.
    # They will only be replaced if they are not empty, otherwise, values from ".env" file will be used.
    environment:
      - LANGUAGE=${LANGUAGE}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      # Exposes the given port from "docker-compose up" instruction from your personal computer.
      - "${PORT}:${PORT}"
      # Named volumes used by different services (follows the syntax "[SOURCE:]TARGET[:MODE]").
# As no TARGET is being set, a default value pointing to "/var/lib/docker/volumes" will be used.
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Named volumes used by different services (follows the syntax "[SOURCE:]TARGET[:MODE]").
# As no TARGET is being set, a default value pointing to "/var/lib/docker/volumes" will be used.
volumes:
  database-data:
