version: '3'
services:
  database_mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # MongoDB uses "/data/db" folder internally to stores its information.
    # We will map it to virtual volume named "database-data", a folder under "/var/lib/docker/volumes"
    # where Docker not gonna have permission issues for reading/writing data.
    # https://stackoverflow.com/questions/61147270/docker-compose-and-mongodb-failed-to-start-up-wiredtiger-under-any-compatibilit
    volumes:
      - database-data:/data/db
  database_mysql:
    image: mysql:5.7
    # Receives variables set from "npm run env:symlink" and attach to the container.
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/docker/volumes/mysql:/var/lib/mysql

  server:
    build: .
    depends_on:
      - database_mongodb
      - database_mysql
    # Receives variables from "docker-compose up" instruction and attach as nodejs "process.env" variables.
    # They will only be replaced if they are not empty, otherwise, values from ".env" file will be used.
    environment:
      - LANGUAGE=${LANGUAGE}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - MONGODB_HOST=${MONGODB_HOST}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      # Exposes the given port from "docker-compose up" instruction from your personal computer.
      - "${PORT}:${PORT}"

# Named volumes used by different services (follows the syntax "[SOURCE:]TARGET[:MODE]").
# As no TARGET is being set, a default value pointing to "/var/lib/docker/volumes" will be used.
volumes:
  database-data:
