version: '3'
services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    # MongoDB uses "/data/db" folder internally to stores its information.
    # We will map it to a "/data/db" under this project's folder.
    volumes:
      - ./data/db:/data/db
  server:
    build: .
    # Receives variables from "docker-compose up" instruction and attach as nodejs "process.env" variables.
    # They will only be replaced if they are not empty, otherwise, values from ".env" file will be used.
    environment:
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - MONGODB_HOST=${MONGODB_HOST}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    depends_on:
      - database
    ports:
      # Exposes the given port from "docker-compose up" instruction from your personal computer.
      - "${PORT}:${PORT}"
